"""Curated transliteration and bilingual synonym mappings for Ethiopian e-commerce.

Maps English terms ↔ Amharic Fidel ↔ Latin Transliterations across all categories.
"""

from typing import Dict, List

# Format: (canonical_term, synonym, category_slug, language)
SYNONYMS_DATA: List[Dict[str, str]] = [
    # --- FURNITURE ---
    {"canonical_term": "sofa", "synonym": "sofa", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "sofa", "synonym": "ሶፋ", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "sofa", "synonym": "soffa", "category_slug": "furniture", "language": "translit"},
    {"canonical_term": "sofa", "synonym": "couch", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "sofa", "synonym": "የሳሎን እቃ", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "sofa", "synonym": "l-shape", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "sofa", "synonym": "ኤል ቅርጽ", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "bed", "synonym": "bed", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "bed", "synonym": "አልጋ", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "bed", "synonym": "alga", "category_slug": "furniture", "language": "translit"},
    {"canonical_term": "bed", "synonym": "mattress", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "bed", "synonym": "ፍራሽ", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "bed", "synonym": "frash", "category_slug": "furniture", "language": "translit"},
    {"canonical_term": "table", "synonym": "table", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "table", "synonym": "ጠረጴዛ", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "table", "synonym": "terepeza", "category_slug": "furniture", "language": "translit"},
    {"canonical_term": "table", "synonym": "dining", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "chair", "synonym": "chair", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "chair", "synonym": "ወንበር", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "chair", "synonym": "wenber", "category_slug": "furniture", "language": "translit"},
    {"canonical_term": "wardrobe", "synonym": "wardrobe", "category_slug": "furniture", "language": "en"},
    {"canonical_term": "wardrobe", "synonym": "ቁም ሳጥን", "category_slug": "furniture", "language": "am"},
    {"canonical_term": "wardrobe", "synonym": "qumsatin", "category_slug": "furniture", "language": "translit"},
    {"canonical_term": "wardrobe", "synonym": "cupboard", "category_slug": "furniture", "language": "en"},

    # --- PHONES & TABLETS ---
    {"canonical_term": "phone", "synonym": "phone", "category_slug": "phones", "language": "en"},
    {"canonical_term": "phone", "synonym": "ስልክ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "phone", "synonym": "silk", "category_slug": "phones", "language": "translit"},
    {"canonical_term": "phone", "synonym": "slk", "category_slug": "phones", "language": "translit"},
    {"canonical_term": "phone", "synonym": "mobile", "category_slug": "phones", "language": "en"},
    {"canonical_term": "phone", "synonym": "ሞባይል", "category_slug": "phones", "language": "am"},
    {"canonical_term": "iphone", "synonym": "iphone", "category_slug": "phones", "language": "en"},
    {"canonical_term": "iphone", "synonym": "አይፎን", "category_slug": "phones", "language": "am"},
    {"canonical_term": "iphone", "synonym": "aifon", "category_slug": "phones", "language": "translit"},
    {"canonical_term": "iphone", "synonym": "apple", "category_slug": "phones", "language": "en"},
    {"canonical_term": "samsung", "synonym": "samsung", "category_slug": "phones", "language": "en"},
    {"canonical_term": "samsung", "synonym": "ሳምሱንግ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "samsung", "synonym": "galaxy", "category_slug": "phones", "language": "en"},
    {"canonical_term": "redmi", "synonym": "redmi", "category_slug": "phones", "language": "en"},
    {"canonical_term": "redmi", "synonym": "ሬድሚ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "redmi", "synonym": "xiaomi", "category_slug": "phones", "language": "en"},
    {"canonical_term": "tecno", "synonym": "tecno", "category_slug": "phones", "language": "en"},
    {"canonical_term": "tecno", "synonym": "ቴክኖ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "tecno", "synonym": "camon", "category_slug": "phones", "language": "en"},
    {"canonical_term": "infinix", "synonym": "infinix", "category_slug": "phones", "language": "en"},
    {"canonical_term": "infinix", "synonym": "ኢንፊኒክስ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "ipad", "synonym": "ipad", "category_slug": "phones", "language": "en"},
    {"canonical_term": "ipad", "synonym": "አይፓድ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "ipad", "synonym": "tablet", "category_slug": "phones", "language": "en"},
    {"canonical_term": "ipad", "synonym": "ታብሌት", "category_slug": "phones", "language": "am"},
    {"canonical_term": "charger", "synonym": "charger", "category_slug": "phones", "language": "en"},
    {"canonical_term": "charger", "synonym": "ቻርጀር", "category_slug": "phones", "language": "am"},
    {"canonical_term": "airpods", "synonym": "airpods", "category_slug": "phones", "language": "en"},
    {"canonical_term": "airpods", "synonym": "ኤርፖድ", "category_slug": "phones", "language": "am"},
    {"canonical_term": "airpods", "synonym": "earbuds", "category_slug": "phones", "language": "en"},

    # --- COMPUTERS & LAPTOPS ---
    {"canonical_term": "laptop", "synonym": "laptop", "category_slug": "computers", "language": "en"},
    {"canonical_term": "laptop", "synonym": "ላፕቶፕ", "category_slug": "computers", "language": "am"},
    {"canonical_term": "laptop", "synonym": "ኮምፒውተር", "category_slug": "computers", "language": "am"},
    {"canonical_term": "laptop", "synonym": "komputer", "category_slug": "computers", "language": "translit"},
    {"canonical_term": "laptop", "synonym": "computer", "category_slug": "computers", "language": "en"},
    {"canonical_term": "laptop", "synonym": "notebook", "category_slug": "computers", "language": "en"},
    {"canonical_term": "macbook", "synonym": "macbook", "category_slug": "computers", "language": "en"},
    {"canonical_term": "macbook", "synonym": "ማክቡክ", "category_slug": "computers", "language": "am"},
    {"canonical_term": "dell", "synonym": "dell", "category_slug": "computers", "language": "en"},
    {"canonical_term": "dell", "synonym": "ዴል", "category_slug": "computers", "language": "am"},
    {"canonical_term": "hp", "synonym": "hp", "category_slug": "computers", "language": "en"},
    {"canonical_term": "hp", "synonym": "ኤችፒ", "category_slug": "computers", "language": "am"},
    {"canonical_term": "lenovo", "synonym": "lenovo", "category_slug": "computers", "language": "en"},
    {"canonical_term": "lenovo", "synonym": "ሌኖቮ", "category_slug": "computers", "language": "am"},
    {"canonical_term": "lenovo", "synonym": "thinkpad", "category_slug": "computers", "language": "en"},
    {"canonical_term": "printer", "synonym": "printer", "category_slug": "computers", "language": "en"},
    {"canonical_term": "printer", "synonym": "ፕሪንተር", "category_slug": "computers", "language": "am"},
    {"canonical_term": "printer", "synonym": "ማተሚያ", "category_slug": "computers", "language": "am"},
    {"canonical_term": "monitor", "synonym": "monitor", "category_slug": "computers", "language": "en"},
    {"canonical_term": "monitor", "synonym": "ሞኒተር", "category_slug": "computers", "language": "am"},
    {"canonical_term": "monitor", "synonym": "ስክሪን", "category_slug": "computers", "language": "am"},

    # --- VEHICLES ---
    {"canonical_term": "car", "synonym": "car", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "car", "synonym": "መኪና", "category_slug": "vehicles", "language": "am"},
    {"canonical_term": "car", "synonym": "mekina", "category_slug": "vehicles", "language": "translit"},
    {"canonical_term": "car", "synonym": "automobile", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "car", "synonym": "አውቶሞቢል", "category_slug": "vehicles", "language": "am"},
    {"canonical_term": "car", "synonym": "vitz", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "toyota", "synonym": "toyota", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "toyota", "synonym": "ቶዮታ", "category_slug": "vehicles", "language": "am"},
    {"canonical_term": "toyota", "synonym": "rav4", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "toyota", "synonym": "yaris", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "toyota", "synonym": "corolla", "category_slug": "vehicles", "language": "en"},
    {"canonical_term": "motorcycle", "synonym": "motorcycle", "category_slug": "vehicles", "language": "en"},
    # "ሞተር" on its own means motor/engine, not motorcycle — it matched inside
    # "ፀጥተኛ ሞተር" (quiet engine) on a generator listing and filed it against
    # motorcycle prices. Same failure mode as "ስልክ" in the offline classifier.
    {"canonical_term": "motorcycle", "synonym": "ሞተር ሳይክል", "category_slug": "vehicles", "language": "am"},
    # A bajaj is a three-wheeler, not a motorcycle: they are different vehicles at
    # very different prices (~440k vs ~85k ETB). Sharing one canonical term made
    # every street bike look 80% underpriced against a bajaj-weighted median.
    {"canonical_term": "bajaj", "synonym": "bajaj", "category_slug": "vehicles", "language": "translit"},
    {"canonical_term": "bajaj", "synonym": "ባጃጅ", "category_slug": "vehicles", "language": "am"},
    {"canonical_term": "bajaj", "synonym": "three wheeler", "category_slug": "vehicles", "language": "en"},


    # --- FASHION & CLOTHING ---
    {"canonical_term": "shoes", "synonym": "shoes", "category_slug": "fashion", "language": "en"},
    {"canonical_term": "shoes", "synonym": "ጫማ", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "shoes", "synonym": "chama", "category_slug": "fashion", "language": "translit"},
    {"canonical_term": "shoes", "synonym": "sneakers", "category_slug": "fashion", "language": "en"},
    {"canonical_term": "shoes", "synonym": "ስኒከር", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "dress", "synonym": "dress", "category_slug": "fashion", "language": "en"},
    {"canonical_term": "dress", "synonym": "ቀሚስ", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "dress", "synonym": "kemis", "category_slug": "fashion", "language": "translit"},
    {"canonical_term": "dress", "synonym": "ጥልፍ", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "dress", "synonym": "ሀበሻ ቀሚስ", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "jacket", "synonym": "jacket", "category_slug": "fashion", "language": "en"},
    {"canonical_term": "jacket", "synonym": "ጃኬት", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "jacket", "synonym": "jakeit", "category_slug": "fashion", "language": "translit"},
    {"canonical_term": "bag", "synonym": "bag", "category_slug": "fashion", "language": "en"},
    {"canonical_term": "bag", "synonym": "ቦርሳ", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "bag", "synonym": "borsa", "category_slug": "fashion", "language": "translit"},
    {"canonical_term": "watch", "synonym": "watch", "category_slug": "fashion", "language": "en"},
    {"canonical_term": "watch", "synonym": "ሰዓት", "category_slug": "fashion", "language": "am"},
    {"canonical_term": "watch", "synonym": "seat", "category_slug": "fashion", "language": "translit"},

    # --- APPLIANCES ---
    {"canonical_term": "fridge", "synonym": "fridge", "category_slug": "appliances", "language": "en"},
    {"canonical_term": "fridge", "synonym": "ፍሪጅ", "category_slug": "appliances", "language": "am"},
    {"canonical_term": "fridge", "synonym": "firij", "category_slug": "appliances", "language": "translit"},
    {"canonical_term": "fridge", "synonym": "refrigerator", "category_slug": "appliances", "language": "en"},
    {"canonical_term": "washing_machine", "synonym": "washing machine", "category_slug": "appliances", "language": "en"},
    {"canonical_term": "washing_machine", "synonym": "ማጠቢያ", "category_slug": "appliances", "language": "am"},
    {"canonical_term": "washing_machine", "synonym": "የልብስ ማጠቢያ", "category_slug": "appliances", "language": "am"},
    {"canonical_term": "microwave", "synonym": "microwave", "category_slug": "appliances", "language": "en"},
    {"canonical_term": "microwave", "synonym": "ማይክሮዌቭ", "category_slug": "appliances", "language": "am"},
    {"canonical_term": "stove", "synonym": "stove", "category_slug": "appliances", "language": "en"},
    {"canonical_term": "stove", "synonym": "ምድጃ", "category_slug": "appliances", "language": "am"},
    {"canonical_term": "stove", "synonym": "ኦቭን", "category_slug": "appliances", "language": "am"},

    # --- TV & AUDIO ---
    {"canonical_term": "tv", "synonym": "tv", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "tv", "synonym": "ቴሌቪዥን", "category_slug": "tv-audio", "language": "am"},
    {"canonical_term": "tv", "synonym": "television", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "tv", "synonym": "smart tv", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "tv", "synonym": "sony", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "tv", "synonym": "lg", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "speaker", "synonym": "speaker", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "speaker", "synonym": "ስፒከር", "category_slug": "tv-audio", "language": "am"},
    {"canonical_term": "speaker", "synonym": "ድምጽ", "category_slug": "tv-audio", "language": "am"},
    {"canonical_term": "speaker", "synonym": "sound system", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "playstation", "synonym": "playstation", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "playstation", "synonym": "ps5", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "playstation", "synonym": "ps4", "category_slug": "tv-audio", "language": "en"},
    {"canonical_term": "playstation", "synonym": "ፕሌይስቴሽን", "category_slug": "tv-audio", "language": "am"},

    # --- KIDS ---
    {"canonical_term": "kids", "synonym": "kids", "category_slug": "kids", "language": "en"},
    {"canonical_term": "kids", "synonym": "የህፃናት", "category_slug": "kids", "language": "am"},
    {"canonical_term": "kids", "synonym": "ህፃናት", "category_slug": "kids", "language": "am"},
    {"canonical_term": "kids", "synonym": "stroller", "category_slug": "kids", "language": "en"},
    {"canonical_term": "kids", "synonym": "የህፃናት ጋሪ", "category_slug": "kids", "language": "am"},
    {"canonical_term": "kids", "synonym": "baby", "category_slug": "kids", "language": "en"},

    # --- TOOLS ---
    {"canonical_term": "drill", "synonym": "drill", "category_slug": "tools", "language": "en"},
    {"canonical_term": "drill", "synonym": "መሰርሰሪያ", "category_slug": "tools", "language": "am"},
    {"canonical_term": "drill", "synonym": "dril", "category_slug": "tools", "language": "translit"},
    {"canonical_term": "drill", "synonym": "bosch", "category_slug": "tools", "language": "en"},
    {"canonical_term": "generator", "synonym": "generator", "category_slug": "tools", "language": "en"},
    {"canonical_term": "generator", "synonym": "ጄኔሬተር", "category_slug": "tools", "language": "am"},
    {"canonical_term": "generator", "synonym": "ዲናሞ", "category_slug": "tools", "language": "am"},
]
