import {
  pgTable,
  uuid,
  integer,
  text,
  jsonb,
  timestamp,
  uniqueIndex,
  index,
} from "drizzle-orm/pg-core"
import { sql } from "drizzle-orm"
import { reservationStatusEnum } from "./enums"
import { listings } from "./listings"
import { users } from "./users"

/**
 * reservations — a Chapa-backed hold on one item.
 *
 * This is deliberately not a checkout. Nobody buys a used sofa sight unseen,
 * and taking the full price online for a peer-to-peer handover we cannot
 * enforce would be a promise we have no way to keep. What a buyer actually
 * wants is for the seller to stop showing it to other people for a day, and
 * what the seller wants is evidence the buyer will turn up. A small deposit
 * through Chapa buys exactly that and nothing more.
 *
 * The row is created *before* Chapa is called, in `pending`, so the tx_ref we
 * send is one we have already written down. A payment that lands for a tx_ref
 * we have never heard of is then unambiguously either a replay or an attack,
 * rather than a race we have to reason about.
 *
 * amount_etb is the deposit. price_etb_at_reservation snapshots what the item
 * cost at the time — a seller editing the price afterwards must not silently
 * change what the buyer agreed to.
 *
 * Money rows are append-only in spirit: status moves forward, and the Chapa
 * payload that moved it is kept in `provider_payload` so a disputed hold can be
 * reconstructed from our own database without asking Chapa what they sent.
 */
export const reservations = pgTable(
  "reservations",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    listingId: uuid("listing_id")
      .notNull()
      .references(() => listings.id),
    buyerId: uuid("buyer_id")
      .notNull()
      .references(() => users.id),
    /** Copied at creation — a listing that changes hands keeps this hold's payee. */
    sellerId: uuid("seller_id")
      .notNull()
      .references(() => users.id),

    /** Deposit actually charged, integer ETB. Never a float, same as prices. */
    amountEtb: integer("amount_etb").notNull(),
    /** What the item was listed at when the hold was taken. */
    priceEtbAtReservation: integer("price_etb_at_reservation"),

    /**
     * Our reference, generated by us and sent to Chapa. Unique because it is
     * the idempotency key for both the webhook and the browser return — the
     * two of them routinely arrive within a second of each other.
     */
    txRef: text("tx_ref").notNull().unique(),
    /** Chapa's own reference, only known after they confirm. */
    providerRef: text("provider_ref"),
    checkoutUrl: text("checkout_url"),

    /**
     * The payment_request message this hold answers, when it started from a
     * seller's request in a conversation rather than from the listing page.
     *
     * This is what makes a request's state derivable instead of stored: a
     * request is paid when a row here points at it and reached `paid`. Storing
     * a status on the message as well would give us two places to be wrong
     * about whether money moved.
     */
    requestMessageId: uuid("request_message_id"),

    /**
     * Where to send the buyer after the checkout.
     *
     * A hold started from a thread must return to that thread — landing back on
     * the listing page after paying inside a conversation loses the context the
     * payment was about. Stored as a path, never a full URL: this value ends up
     * in a redirect, and accepting a host here would make the return an open
     * redirect for anyone who could write the column.
     */
    returnPath: text("return_path"),

    status: reservationStatusEnum("status").notNull().default("pending"),

    /** When the hold lapses if nothing else happens. */
    expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(),
    paidAt: timestamp("paid_at", { withTimezone: true }),

    /** Last verified/webhook payload, for dispute reconstruction. */
    providerPayload: jsonb("provider_payload"),

    createdAt: timestamp("created_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true })
      .notNull()
      .defaultNow(),
  },
  (t) => [
    /**
     * At most one live hold per listing. Partial, so the dozens of expired and
     * cancelled rows a popular item accumulates never block the next buyer —
     * enforcing this in Postgres rather than in the route is what makes two
     * simultaneous "reserve" taps resolve to one winner and one 409.
     */
    uniqueIndex("reservations_one_active_per_listing_uidx")
      .on(t.listingId)
      .where(sql`status in ('pending', 'paid')`),
    index("reservations_listing_status_idx").on(t.listingId, t.status),
    index("reservations_buyer_id_idx").on(t.buyerId),
    index("reservations_seller_id_idx").on(t.sellerId),
    // The expiry sweep: pending/paid rows whose window has closed.
    index("reservations_expires_at_idx").on(t.expiresAt),
  ]
)
